[project]
name = "amazing-travel-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=0.3.3",
    "langgraph>=0.4.8",
    "typing-extensions>=4.14.0",
]
